FROM arm64v8/ubuntu:jammy

ENV DEBIAN_FRONTEND noninteractive
ENV TERMINAL linux

ENV CHECKOUT HEAD NCORES

ENV ARCH arm64
ENV ABI aarch64-linux-gnu

RUN apt-get update && apt-get install -y \
    libc6-dev \
    libwebsockets-dev \
	pkg-config \
	zlib1g-dev \
	libnl-3-dev \
	libnl-genl-3-dev \
	libcap-dev \
	libpcap-dev \
	libnm-dev \
	libdw-dev \
	libsqlite3-dev \
	libprotobuf-dev \
	libprotobuf-c-dev \
	protobuf-compiler \
	protobuf-c-compiler \
	libsensors4-dev \
	librtlsdr0 \
    librtlsdr-dev \
	libusb-1.0-0-dev \
    libubertooth-dev \
    libbtbb-dev \
    libubertooth1 \
    libbtbb1 \
    libbladerf2 \
    libbladerf-dev \
    libmosquitto-dev

